Name:           ros-kinetic-visualization-tutorials
Version:        0.10.2
Release:        0%{?dist}
Summary:        ROS visualization_tutorials package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/visualization_tutorials
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-interactive-marker-tutorials
Requires:       ros-kinetic-librviz-tutorial
Requires:       ros-kinetic-rviz-plugin-tutorials
Requires:       ros-kinetic-rviz-python-tutorial
Requires:       ros-kinetic-visualization-marker-tutorials
BuildRequires:  ros-kinetic-catkin

%description
Metapackage referencing tutorials related to rviz and visualization.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Fri Jan 05 2018 William Woodall <william@osrfoundation.org> - 0.10.2-0
- Autogenerated by Bloom

* Thu Apr 21 2016 William Woodall <william@osrfoundation.org> - 0.10.1-0
- Autogenerated by Bloom

* Thu Apr 21 2016 William Woodall <william@osrfoundation.org> - 0.10.0-0
- Autogenerated by Bloom

